export const Overrides = {
  SHAME_OVERRIDE:            null,
  REPUTATION_OVERRIDE:       null,
  TECHNICAL_DEBT_OVERRIDE:   null,
  HP_OVERRIDE:               null,
  LEVEL_OVERRIDE:            null,
  LOCATION_OVERRIDE:         null,
  ACT_OVERRIDE:              null,
  FLAGS_OVERRIDE:            null,
  INFINITE_SLA:              null,
  DOMAIN_REVEALED_OVERRIDE:  null,
  OPPONENT_DOMAIN_OVERRIDE:  null,
  STARTER_DECK:              null,
  STARTER_ITEMS:             null,
}
